---
- hosts: localhost
  become: true
  vars:
    db_volume: mariadb
    wordpress: wordpress
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Make sure that docker was started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy MariaDB server
      docker_container:
        image: mariadb
        name: mariadb
        volumes:
          - "{{db_volume}}:/var/lib/mysql"
        env:
          MYSQL_ROOT_PASSWORD: somerootpassword
          MYSQL_PASSWORD: somemysqlpassword
          MYSQL_DATABASE: db
          MYSQL_USER: mysqluser

    - name: Deploy WordPress
      docker_container:
        image: wordpress
        name: wordpress
        restart_policy: always
        ports:
          - "80:80"
        links:
          - "{{db_volume}}:/var/lib/mysql"
        volumes:
          - "{{wordpress}}:/var/www/html"
        env:
          MYSQL_PASSWORD: somemysqlpassword
          MYSQL_DATABASE: db
          MYSQL_USER: mysqluser
          MYSQL_HOST: mariadb
